kind: Deployment
apiVersion: apps/v1
metadata:
  name: camel-cicd-demi-deploymnet
  namespace: appdev-demo
 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camel-cicd-demi-deploymnet
  template:
    metadata:
     
      labels:
        app: camel-cicd-demi-deploymnet
    spec:
      containers:
        - name: camel-cicd-demi-deploymnet
          image: 'quay.io/jmaira/demos:latest'
          ports:
            - name: 8081-tcp
              containerPort: 8081
              protocol: TCP
          envFrom:
            - configMapRef:
                name: camel-cicd-demo-cm
