kind: Deployment
apiVersion: apps/v1
metadata:
  name: appdev-cicd-demo-deploymnet
  
 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appdev-cicd-demi-deploymnet
  template:
    metadata:
     
      labels:
        app: appdev-cicd-demi-deploymnet
    spec:
      containers:
        - name: appdev-cicd-demi-deploymnet
          image: 'quay.io/jmaira/demos:latest'
          ports:
            - name: 8081-tcp
              containerPort: 8081
              protocol: TCP
          envFrom:
            - configMapRef:
                name: camel-cicd-demo-cm
